-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguHrJENByUpf6sEO3
6OLxBARVrDCSyYLYxBdYVAG7JI2gCgYIKoZIzj0DAQehRANCAATjUEGcoSDa4zsI
OvuI79urEiI1VN/ydvCOn3KjmFiWl4WrUo9zY1OU8/4vRuhrmwynd7Z+vn5YDwC/
1tg1Czkz
-----END PRIVATE KEY-----